apiVersion: skaffold/v4beta10 
kind: Config
manifests:
 rawYaml:
 - ./infra/k8s/*
deploy:
 kubectl: {}
build:
  local:
    push: false
  artifacts:
    - image: sachida/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: sachida/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: sachida/event_bus
      context: event_bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: sachida/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: sachida/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: sachida/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "./src/**/*.js"
            dest: .